# Generated by Django 3.1.3 on 2022-04-29 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('name', models.TextField()),
                ('steps', models.TextField(blank=True, default='')),
                ('fact_result', models.TextField(blank=True, default='')),
                ('exp_result', models.TextField(blank=True, default='')),
                ('desc', models.TextField(blank=True, default='')),
                ('priority', models.TextField(choices=[('Высокий', 'P1'), ('Средний', 'P2'), ('Низкий', 'P3')])),
                ('severity', models.TextField(choices=[('Блокирующий', 'S1'), ('Критический', 'S2'), ('Значительный', 'S3'), ('Незначительный', 'S4'), ('Тривиальный', 'S5')])),
                ('status', models.TextField(choices=[('Новый', 'New'), ('Открыт', 'Open'), ('Закрытый', 'Closed')])),
                ('url', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugreports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
